name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build the .deb package
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        chmod +x build.sh
        ./build.sh ${{ github.ref_name }}

    - name: Upload .deb to release
      uses: softprops/action-gh-release@v1
      with:
        files: ./tpp-df-bt-service_${{ github.ref_name }}-1_all.deb