name: Build and Release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build the .deb package
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        chmod +x build.sh
        ./build.sh ${{ github.ref_name }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: ./tpp-df-bt-service_*-1_all.deb

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
      - name: Upload .deb to release
        uses: softprops/action-gh-release@v1
        with:
          files: tpp-df-bt-service_*-1_all.deb
